=== powsybl/powsybl-entsoe/glsk/glsk-document-cse/src/main/resources/xsd/gsk-document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by RTE (RTE) -->
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by baracchini (RTE) -->
<xsd:schema xmlns:ecc="etso-core-cmpts.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd"/>
	<!--_________________________________________________-->
	<!--                            GSK Document Version V7 R0            -->
	<!--_________________________________________________-->
	<xsd:element name="GSKDocument">
		<xsd:complexType>
			<xsd:annotation>
				<xsd:documentation/>
			</xsd:annotation>
			<xsd:sequence>
				<xsd:element name="DocumentIdentification" type="ecc:LongIdentificationType"/>
				<xsd:element name="DocumentVersion" type="ecc:VersionType"/>
				<xsd:element name="DocumentScenario" type="T_DocumentScenario" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="DocumentType" type="ecc:MessageType"/>
				<xsd:element name="ProcessType" type="ecc:ProcessType"/>
				<xsd:element name="SenderIdentification" type="ecc:PartyType"/>
				<xsd:element name="SenderRole" type="ecc:RoleType"/>
				<xsd:element name="ReceiverIdentification" type="ecc:PartyType"/>
				<xsd:element name="ReceiverRole" type="ecc:RoleType"/>
				<xsd:element name="CreationDateTime" type="ecc:MessageDateTimeType"/>
				<xsd:element name="GSKTimeInterval" type="ecc:TimeIntervalType"/>
				<xsd:element name="Domain" type="ecc:AreaType"/>
				<xsd:element name="CalculationDirections" type="CalculationDirectionsType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="TimeSeries" type="TimeSeriesType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="TimeSeriesExport" type="TimeSeriesType" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="Reason" type="ReasonType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="DtdRelease" type="xsd:string" use="optional"/>
			<xsd:attribute name="DtdVersion" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<!--_________________________________________________-->
	<xsd:complexType name="T_DocumentScenario">
		<xsd:attribute name="v" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Transit"/> 
					<xsd:enumeration value="Import"/>
					<xsd:enumeration value="Export"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="T_Direction">
		<xsd:attribute name="v" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Import"/>
					<xsd:enumeration value="Export"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
	<!--_________________________________________________-->
	<xsd:complexType name="TimeSeriesType">
		<xsd:sequence>
			<xsd:element name="TimeSeriesIdentification" type="ecc:IdentificationType"/>
			<xsd:element name="BusinessType" type="ecc:BusinessType"/>
			<xsd:element name="Area" type="ecc:AreaType"/>
			<xsd:element name="Name" type="ecc:IdentificationType"/>
			<xsd:element name="TimeInterval" type="ecc:TimeIntervalType"/>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="PropGSKBlock" type="PropGSKBlockType"/>
				<xsd:element name="ReserveGSKBlock" type="ReserveGSKBlockType"/>
				<xsd:element name="MeritOrderGSKBlock" type="MeritOrderGSKBlockType"/>
				<xsd:element name="ManualGSKBlock" type="ManualGSKBlockType"/>
				<xsd:element name="ReferenceGSKBlock" type="ReferenceGSKBlockType"/>
			</xsd:choice>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="ManusequenceSKBlock" type="ManusequenceSKBlockType"/>
				<xsd:element name="PropLSKBlock" type="PropLSKBlockType"/>
				<!--<xsd:element name="CalculationDirections" type="CalculationDirectionsType"/>-->
			</xsd:choice>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ReferenceGSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="MaximumShift" type="ecc:QuantityType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Area" type="ecc:AreaType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PropGSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="MaximumShift" type="ecc:QuantityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Node" type="PropGSKNodeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PropGSKNodeType">
		<xsd:sequence>
			<xsd:element name="Name" type="NodeNameType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PropLSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Node" type="PropLSKNodeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PropLSKNodeType">
		<xsd:sequence>
			<xsd:element name="Name" type="NodeNameType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManualGSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Node" type="ManualGSKNodeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManualGSKNodeType">
		<xsd:sequence>
			<xsd:element name="Name" type="NodeNameType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManusequenceSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Node" type="ManusequenceSKNodeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManusequenceSKNodeType">
		<xsd:sequence>
			<xsd:element name="Name" type="NodeNameType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CalculationDirectionsType">
		<xsd:sequence>
			<xsd:element name="CalculationDirection" type="CalculationDirectionType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CalculationDirectionType">
		<xsd:sequence>
			<xsd:element name="Direction" type="T_Direction" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Country" type="ecc:IdentificationType" minOccurs="1" maxOccurs="unbounded"/>
			<xsd:element name="InArea" type="ecc:AreaType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="OutArea" type="ecc:AreaType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ReserveGSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Node" type="ReserveGSKNodeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ReserveGSKNodeType">
		<xsd:sequence>
			<xsd:element name="Name" type="NodeNameType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Pmin" type="ecc:QuantityType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Pmax" type="ecc:QuantityType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MeritOrderGSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="ecc:QuantityType" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Up" type="MeritOrderUpGSKBlockType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Down" type="MeritOrderDownGSKBlockType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MeritOrderUpGSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="MeritOrderFactorType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Node" type="MeritOrderUpNodeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MeritOrderUpNodeType">
		<xsd:sequence>
			<xsd:element name="Name" type="NodeNameType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Pmax" type="ecc:QuantityType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MeritOrderDownGSKBlockType">
		<xsd:sequence>
			<xsd:element name="Order" type="xsd:integer" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="Factor" type="MeritOrderFactorType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Node" type="MeritOrderDownNodeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="MeritOrderDownNodeType">
		<xsd:sequence>
			<xsd:element name="Name" type="NodeNameType" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="Pmin" type="ecc:QuantityType" minOccurs="1" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="NodeNameType">
		<xsd:attribute name="v" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value=".{6}\d[' '-~]"/>
					<!-- the last character can be any ASCII + <blank> +  -->
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="MeritOrderFactorType">
		<xsd:attribute name="v" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1"/>
					<xsd:maxInclusive value="999"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="ReasonType">
		<xsd:sequence>
			<xsd:element name="ReasonCode" type="ecc:ReasonCodeType"/>
			<xsd:element name="ReasonText" type="ecc:ReasonTextType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== powsybl/powsybl-entsoe/glsk/glsk-document-cse/src/test/resources/testGlskWithInitialLimits.xml
<?xml version="1.0" encoding="utf-8"?>
<GSKDocument DtdVersion="5" DtdRelease="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document.xsd">
    <DocumentIdentification v="testGlsk"/>
    <DocumentVersion v="1"/>
    <DocumentType v="Z02"/>
    <ProcessType v="Z02"/>
    <SenderIdentification v="10VCSEEH4MMD-NDO" codingScheme="A01"/>
    <SenderRole v="A36"/>
    <ReceiverIdentification v="10X1001A1001A345" codingScheme="A01"/>
    <ReceiverRole v="A04"/>
    <CreationDateTime v="2020-09-15T17:59:09Z"/>
    <GSKTimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
    <Domain v="10YDOM-1001A061T" codingScheme="A01"/>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="BE_RESERVE" codingScheme="A01"/>
        <Name v="BE_RESERVE"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <ReserveGSKBlock>
            <Factor v="1"/>
            <Node>
                <Name v="BBE1AA1 "/>
                <Pmin v="0"/>
                <Pmax v="-9000"/>
            </Node>
            <Node>
                <Name v="BBE3AA1 "/>
                <Pmin v="-1000"/>
                <Pmax v="-9000"/>
            </Node>
        </ReserveGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="NL_RESERVE" codingScheme="A01"/>
        <Name v="NL_RESERVE"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <ReserveGSKBlock>
            <Factor v="1"/>
            <Node>
                <Name v="NNL1AA1 "/>
                <Pmin v="0"/>
                <Pmax v="-1500"/>
            </Node>
            <Node>
                <Name v="NNL2AA1 "/>
                <Pmin v="-1000"/>
                <Pmax v="-9000"/>
            </Node>
        </ReserveGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="FR_RESERVE" codingScheme="A01"/>
        <Name v="FR_RESERVE"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <ReserveGSKBlock>
            <Factor v="1"/>
            <Node>
                <Name v="FFR1AA1 "/>
                <Pmin v="0"/>
                <Pmax v="-9000"/>
            </Node>
            <Node>
                <Name v="FFR2AA1 "/>
                <Pmin v="-1000"/>
                <Pmax v="-2000"/>
            </Node>
        </ReserveGSKBlock>
    </TimeSeries>
</GSKDocument>

=== powsybl/powsybl-entsoe/glsk/glsk-document-cse/src/test/resources/testGlskHybrid.xml
<?xml version="1.0" encoding="utf-8"?>
<GSKDocument DtdVersion="5" DtdRelease="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document.xsd">
    <DocumentIdentification v="testGlsk"/>
    <DocumentVersion v="1"/>
    <DocumentType v="Z02"/>
    <ProcessType v="Z02"/>
    <SenderIdentification v="XXXXXXXXXXXXXXXX" codingScheme="A01"/>
    <SenderRole v="A36"/>
    <ReceiverIdentification v="XXXXXXXXXXXXXXXX" codingScheme="A01"/>
    <ReceiverRole v="A04"/>
    <CreationDateTime v="2020-09-15T17:59:09Z"/>
    <GSKTimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
    <Domain v="10YDOM-1001A061T" codingScheme="A01"/>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YCH-SWISSGRIDZ" codingScheme="A01" />
        <Name v="CH" />
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <PropGSKBlock>
            <Order>1</Order>
            <MaximumShift v="1000" />
<!--            <Factor v="1"/>-->
            <Node>
                <Name v="FFR1AA1 "/>
            </Node>
            <Node>
                <Name v="FFR2AA1 "/>
            </Node>
        </PropGSKBlock>
        <ReserveGSKBlock>
            <Order>2</Order>
<!--            <Factor v="1"/>-->
            <Node>
                <Name v="FFR3AA1 "/>
                <Pmin v="0"/>
                <Pmax v="-5000"/>
            </Node>
        </ReserveGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="FR_MANUAL" codingScheme="A01"/>
        <Name v="FR_MANUAL"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <ManualGSKBlock>
            <Factor v="1"/>
            <Node>
                <Name v="FFR1AA1 "/>
                <Factor v="70"/>
            </Node>
            <Node>
                <Name v="FFR3AA1 "/>
                <Factor v="30"/>
            </Node>
        </ManualGSKBlock>
    </TimeSeries>
</GSKDocument>

=== powsybl/powsybl-entsoe/glsk/glsk-document-cse/src/test/resources/testGlskMerged.xml
<?xml version="1.0" encoding="utf-8"?>
<GSKDocument DtdVersion="5" DtdRelease="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document.xsd">
    <DocumentIdentification v="testGlskMerged"/>
    <DocumentVersion v="1"/>
    <DocumentType v="Z02"/>
    <ProcessType v="Z02"/>
    <SenderIdentification v="10VCSEEH4MMD-NDO" codingScheme="A01"/>
    <SenderRole v="A36"/>
    <ReceiverIdentification v="10X1001A1001A345" codingScheme="A01"/>
    <ReceiverRole v="A04"/>
    <CreationDateTime v="2020-09-15T17:59:09Z"/>
    <GSKTimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
    <Domain v="10YDOM-1001A061T" codingScheme="A01"/>

    <CalculationDirections>
        <CalculationDirection>
            <Direction v="Export"/>
            <Country v="AT"/>
            <InArea v="10YAT-APG------L" codingScheme="A01"/>
            <OutArea v="10YIT-GRTN-----B" codingScheme="A01"/>
        </CalculationDirection>
        <CalculationDirection>
            <Direction v="Import"/>
            <Country v="CH"/>
            <InArea v="10YIT-GRTN-----B" codingScheme="A01"/>
            <OutArea v="10YCH-SWISSGRIDZ" codingScheme="A01"/>
        </CalculationDirection>
        <CalculationDirection>
            <Direction v="Import"/>
            <Country v="FR"/>
            <InArea v="10YIT-GRTN-----B" codingScheme="A01"/>
            <OutArea v="10YFR-RTE------C" codingScheme="A01"/>
        </CalculationDirection>
        <CalculationDirection>
            <Direction v="Export"/>
            <Country v="SI"/>
            <InArea v="10YSI-ELES-----O" codingScheme="A01"/>
            <OutArea v="10YIT-GRTN-----B" codingScheme="A01"/>
        </CalculationDirection>
    </CalculationDirections>

    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YAT-APG------L" codingScheme="A01"/>
        <Name v="AT"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
        <ManualGSKBlock>
            <Factor v="1"/>
            <Node>
                <Name v="AT01AA01"/>
                <Factor v="40"/>
            </Node>
            <Node>
                <Name v="AT02AA01"/>
                <Factor v="60"/>
            </Node>
        </ManualGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YCH-SWISSGRIDZ" codingScheme="A01"/>
        <Name v="CH"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <ReserveGSKBlock>
            <Factor v="1.2"/>
            <Node>
                <Name v="CH01AA01"/>
                <Pmin v="10"/>
                <Pmax v="-200"/>
            </Node>
        </ReserveGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YFR-RTE------C" codingScheme="A01"/>
        <Name v="FR"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
        <PropGSKBlock>
            <Factor v="1.05"/>
            <Node>
                <Name v="FR01AA01"/>
            </Node>
            <Node>
                <Name v="FR02AA01"/>
            </Node>
            <Node>
                <Name v="FR03AA01"/>
            </Node>
        </PropGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YIT-GRTN-----B" codingScheme="A01"/>
        <Name v="IT"/>
        <TimeInterval v="2020-09-16T22:30Z/2020-09-16T22:30Z"/>
        <MeritOrderGSKBlock>
            <Factor v="1.15"/>
            <Up>
                <Factor v="1"/>
                <Node>
                    <Name v="IT01AA01"/>
                    <Pmax v="-1000"/>
                </Node>
            </Up>
            <Down>
                <Factor v="1"/>
                <Node>
                    <Name v="IT01AA02"/>
                    <Pmin v="0"/>
                </Node>
            </Down>
        </MeritOrderGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YSI-ELES-----O" codingScheme="A01"/>
        <Name v="SI"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
        <PropGSKBlock>
            <Factor v="0.7"/>
            <Node>
                <Name v="SI01AA01"/>
            </Node>
        </PropGSKBlock>
        <PropLSKBlock>
            <Factor v="0.3"/>
            <Node>
                <Name v="SI02AA01"/>
            </Node>
            <Node>
                <Name v="SI02AA02"/>
            </Node>
        </PropLSKBlock>
    </TimeSeries>

    <TimeSeriesExport>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YAT-APG------L" codingScheme="A01"/>
        <Name v="AT"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
        <ManualGSKBlock>
            <Factor v="0.95"/>
            <Node>
                <Name v="AT01AA01"/>
                <Factor v="70"/>
            </Node>
            <Node>
                <Name v="AT02AA01"/>
                <Factor v="30"/>
            </Node>
        </ManualGSKBlock>
    </TimeSeriesExport>
    <TimeSeriesExport>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="10YFR-RTE------C" codingScheme="A01"/>
        <Name v="FR"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
        <PropGSKBlock>
            <Factor v="0.25"/>
            <Node>
                <Name v="FR01AA01"/>
            </Node>
        </PropGSKBlock>
        <PropLSKBlock>
            <Factor v="0.75"/>
            <Node>
                <Name v="FR02AA01"/>
            </Node>
            <Node>
                <Name v="FR03AA01"/>
            </Node>
        </PropLSKBlock>
    </TimeSeriesExport>
</GSKDocument>

=== powsybl/powsybl-entsoe/glsk/glsk-document-cse/src/test/resources/testGlskOnlyLinear.xml
<?xml version="1.0" encoding="utf-8"?>
<GSKDocument DtdVersion="5" DtdRelease="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gsk-document.xsd">
    <DocumentIdentification v="testGlsk"/>
    <DocumentVersion v="1"/>
    <DocumentType v="Z02"/>
    <ProcessType v="Z02"/>
    <SenderIdentification v="10VCSEEH4MMD-NDO" codingScheme="A01"/>
    <SenderRole v="A36"/>
    <ReceiverIdentification v="10X1001A1001A345" codingScheme="A01"/>
    <ReceiverRole v="A04"/>
    <CreationDateTime v="2020-09-15T17:59:09Z"/>
    <GSKTimeInterval v="2020-09-16T22:00Z/2020-09-16T23:00Z"/>
    <Domain v="10YDOM-1001A061T" codingScheme="A01"/>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="FR_MANUAL" codingScheme="A01"/>
        <Name v="FR_MANUAL"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <ManualGSKBlock>
            <Factor v="1"/>
            <Node>
                <Name v="FFR1AA1 "/>
                <Factor v="70"/>
            </Node>
            <Node>
                <Name v="FFR3AA1 "/>
                <Factor v="30"/>
            </Node>
        </ManualGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="FR_PROPGSK" codingScheme="A01"/>
        <Name v="FR_PROPGSK"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <PropGSKBlock>
            <Factor v="1"/>
            <Node>
                <Name v="FFR1AA1 "/>
            </Node>
            <Node>
                <Name v="FFR2AA1 "/>
            </Node>
            <Node>
                <Name v="FFR3AA1 "/>
            </Node>
        </PropGSKBlock>
    </TimeSeries>
    <TimeSeries>
        <TimeSeriesIdentification v="1"/>
        <BusinessType v="Z02"/>
        <Area v="FR_PROPGLSK" codingScheme="A01"/>
        <Name v="FR_PROPGLSK"/>
        <TimeInterval v="2020-09-16T22:00Z/2020-09-16T22:59Z"/>
        <PropGSKBlock>
            <Factor v="0.7"/>
            <Node>
                <Name v="FFR1AA1 "/>
            </Node>
            <Node>
                <Name v="FFR2AA1 "/>
            </Node>
            <Node>
                <Name v="FFR3AA1 "/>
            </Node>
        </PropGSKBlock>
        <PropLSKBlock>
            <Factor v="0.3"/>
            <Node>
                <Name v="FFR1AA1 "/>
            </Node>
            <Node>
                <Name v="FFR2AA1 "/>
            </Node>
        </PropLSKBlock>
    </TimeSeries>
</GSKDocument>
